// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJGnmxlMSpKSjcYzE204sR3BblLESwVN0',
    appId: '1:38015458388:web:efebab6825000c554c61c1',
    messagingSenderId: '38015458388',
    projectId: 'speechassistiveapp-2d136',
    authDomain: 'speechassistiveapp-2d136.firebaseapp.com',
    storageBucket: 'speechassistiveapp-2d136.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl5Y2sqfG9AdNhMS70apTBEIv41fXgwmg',
    appId: '1:38015458388:android:63ce70976e8a06e24c61c1',
    messagingSenderId: '38015458388',
    projectId: 'speechassistiveapp-2d136',
    storageBucket: 'speechassistiveapp-2d136.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCgxpY4fs7HrgCQW1AADt4Ei7fUx1F8_M',
    appId: '1:38015458388:ios:0bd831764c82cf784c61c1',
    messagingSenderId: '38015458388',
    projectId: 'speechassistiveapp-2d136',
    storageBucket: 'speechassistiveapp-2d136.appspot.com',
    iosClientId: '38015458388-id9faih5mlurp82028cdtqbanej0t24d.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCgxpY4fs7HrgCQW1AADt4Ei7fUx1F8_M',
    appId: '1:38015458388:ios:aa41a6a906b387344c61c1',
    messagingSenderId: '38015458388',
    projectId: 'speechassistiveapp-2d136',
    storageBucket: 'speechassistiveapp-2d136.appspot.com',
    iosClientId: '38015458388-ndr2g6e5j1prddndf5vsc9bma5r61lsp.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginFlutterApp.RunnerTests',
  );
}
